---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-annot-resource-modif-ericsson-com-v1-resourcemodifier
  failurePolicy: Fail
  name: mresourcemodifier-v1.kb.io
  rules:
  - apiGroups:
    - annot-resource-modif.ericsson.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcemodifiers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-annot-resource-modif-ericsson-com-v1-resourcemodifier
  failurePolicy: Fail
  name: vresourcemodifier-v1.kb.io
  rules:
  - apiGroups:
    - annot-resource-modif.ericsson.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcemodifiers
  sideEffects: None
