---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - annot-resource-modif.ericsson.com
  resources:
  - resourcemodifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - annot-resource-modif.ericsson.com
  resources:
  - resourcemodifiers/finalizers
  verbs:
  - update
- apiGroups:
  - annot-resource-modif.ericsson.com
  resources:
  - resourcemodifiers/status
  verbs:
  - get
  - patch
  - update
